Manage workloads on guest clusters

diff --git a/bingo.yml b/bingo.yml
--- a/bingo.yml
+++ b/bingo.yml
@@ -79,6 +79,7 @@ spec:
         - --ssh-known-hosts=false
         - --ssh-known-hosts-file=/dev/null
         - --dest=repo #! will become '--link'
+        - --wait=60 #! will become '--period'
         env:
         - name: GIT_SYNC_REPO
           valueFrom:
@@ -89,9 +90,9 @@ spec:
         - name: GIT_SYNC_REV
           valueFrom:
             configMapKeyRef: { name: bingo-config, key: rev }
-        - name: GIT_SYNC_PERIOD
-          valueFrom:
-            configMapKeyRef: { name: bingo-config, key: period }
+        #! - name: GIT_SYNC_PERIOD
+        #!   valueFrom:
+        #!     configMapKeyRef: { name: bingo-config, key: period }
         - name: GIT_SYNC_EXECHOOK_COMMAND
           value: /scripts/poke.sh
         volumeMounts:
@@ -158,34 +159,120 @@ data:
 
     apply() {
       local cmd="$1"
-      local clusterConf
+      local clusterConf workloadConf
+      local ns cluster
 
-      echo >&2 "apply: ${cmd}"
-
-      # create some clusters
-      while read -r -d $'\0' clusterConf
+      # delete some cluster workload
+      while read -r -d $'\0' workloadConf
       do
-        kubectl apply -f "$clusterConf"
-      done < <( find . -type f -name cluster.yml -print0 )
+        IFS=/ read -r _ ns cluster _ <<< "$workloadConf"
+        runLogged "${ns}/${cluster}" deleteClusterWorkload "$ns" "$cluster" "$workloadConf"
+      done < <( find . -type f -name workload.yml.delete -print0 )
 
       # delete some clusters
-      while read -r -d $'\0' clusterConf
+      while read -d $'\0' -r clusterConf
       do
-        kubectl delete -f "$clusterConf"
+        IFS=/ read -r _ ns cluster _ <<< "$clusterConf"
+        runLogged "${ns}/${cluster}" deleteCluster "$clusterConf"
       done < <( find . -type f -name cluster.yml.delete -print0 )
+
+      # create some clusters
+      while read -d $'\0' -r clusterConf
+      do
+        IFS=/ read -r _ ns cluster _ <<< "$clusterConf"
+        runLogged "${ns}/${cluster}" applyCluster "$clusterConf"
+      done < <( find . -type f -name cluster.yml -print0 )
+
+      # create some cluster workload
+      while read -r -d $'\0' workloadConf
+      do
+        IFS=/ read -r _ ns cluster _ <<< "$workloadConf"
+        runLogged "${ns}/${cluster}" applyClusterWorkload "$ns" "$cluster" "$workloadConf"
+      done < <( find . -type f -name workload.yml -print0 )
+    }
+
+    applyCluster() {
+      echo >&2 "applying:"
+      kubectl apply -f "$1" || {
+        echo >&2 'Issues on apply!'
+        return # well, ignore and retry on next cycle
+      }
+      echo >&2 "applying done."
+    }
+
+    deleteCluster() {
+      echo >&2 "deleting:"
+      kubectl delete -f "$1" || {
+        echo >&2 'Issues on deletion!'
+        return # well, ignore and retry on next cycle
+      }
+      echo >&2 "deleting done."
+    }
+
+    applyClusterWorkload() {
+      echo >&2 "applying workload to remote cluster $1/$2:"
+      kubectl --kubeconfig <(getKubeconf "$1" "$2") apply -f "$3" || {
+        echo >&2 'Issues on apply!'
+        return # well, ignore and retry on next cycle
+      }
+      echo >&2 "applying done."
+    }
+
+    deleteClusterWorkload() {
+      echo >&2 "deleting workload on remote cluster $1/$2:"
+      kubectl --kubeconfig <(getKubeconf "$1" "$2") delete -f "$3" || {
+        echo >&2 'Issues on deletion!'
+        return # well, ignore and retry on next cycle
+      }
+      echo >&2 "deleting done."
+    }
+
+    getKubeconf() {
+      kubectl --namespace "$1" get secret "${2}-kubeconfig" \
+        -o go-template='{{ .data.value | base64decode }}'
+    }
+
+    runLogged() {
+      local logPrefix="$1"
+      shift
+
+      "$@" \
+          >  >( awk -v p="${logPrefix},O" '{ print p ": " $0 }' ) \
+          2> >( awk -v p="${logPrefix},E" '{ print p ": " $0 }' >&2 )
     }
 
     main() {
       local cmd
-      while read -r cmd < /shared/pipe
+
+      while true
       do
-        # cd, because the link might have changed
-        cd "/data/repo/${BINGO_SUB_DIR}"
-        apply "$cmd"
-      done < /shared/pipe
+        read -r cmd < /shared/pipe
+
+        case "$cmd" in
+          reload)
+            echo >&2 'reloading bingo runner'
+            exec "$0" "$@"
+            ;;
+          exit|quit|stop)
+            echo >&2 'stopping bingo runner'
+            exit 10
+            ;;
+          *)
+            cd "/data/repo/${BINGO_SUB_DIR}"
+            echo >&2 "got '$cmd', running apply in ${PWD}"
+            apply "$cmd"
+            ;;
+        esac
+      done
     }
 
-    main "$@"
+    rc=0
+    main "$@" || rc=$?
+
+    if [[ $rc -gt 0 ]] ; then
+      echo >&2 "bingo runner's main exited with: $rc"
+      exit $rc
+    fi
   poke.sh: |
     #!/bin/sh
 
@@ -203,7 +290,7 @@ data:
   repo: git@github.com:hoegaarden/bingo
   branch: main
   rev: HEAD
-  period: 1m
+  #! period: 1m
   dir: example
 ---
 #! apiVersion: v1
